server:
  port: 8080
  server:
    servlet:
      context-path= /tech
spring:
  datasource:
    password: 123456aA@
    url: jdbc:mysql://localhost:3306/shopmedb
    username: root
  main:
    allow-circular-references: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: null
            client-secret: null
            scope:
              - email
              - profile
          facebook:
            client-id: null
            client-secret: null
            scope:
              - email
              - public_profile