server:
  port: 8080
  server:
    servlet:
      context-path= /tech
spring:
  datasource:
    password: 123456aA@
    url: jdbc:mysql://localhost:3306/shopmedb
    username: root
  main:
    allow-circular-references: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 160886045569-ts8b0maeu29gu8a2kafatu0ek1747681.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          facebook:
            client-id: 178488898208605
            client-secret: 5c64dd7a4fe2442e07269276138c626c
            scope:
              - email
              - public_profile